function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 19:45:34.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [2.7853670885810122293;-1.7476024166461932019;-0.72954859362029200742;-0.77847074707098651292;-0.27785003550715142717;0.23108905795477513445;0.55792118163813453346;1.0101492655110926311;-2.0331170647937528706;-0.55060885789199176532];
IW1_1 = [-1.8108474339953908316 -4.148169067273534516 -0.82419839413024942321 1.1843159777525462673;-0.03389748911196550224 -1.905006176602144885 0.37429670481283855432 -0.10325548073375304114;0.56910713655670375211 -1.9194602019348623312 0.84666076799990053203 -0.88805495529362477036;0.017837108587909478868 -0.7353362434752518384 -0.34871719091051817108 0.067198759694015910982;2.5061865871972086595 -1.5332723277623070413 -1.8838468778902752732 -0.94977649153007859262;0.0058301695435026314185 0.33794358382812467179 -0.062079138955163724878 0.0059070257107566425531;0.16481957926542090132 -1.5547430209915378274 1.0439266865193697065 -1.7042233077810970965;0.7275021625080289045 0.97027308501166931176 0.024291347956715961254 -1.9724684772507079522;-2.5193240346754741665 1.9565894639371559371 -1.2579933223171344547 -1.336001897301871244;-0.0068990836217195858349 0.37111318307515872572 0.14266605866244622125 -0.0036803024010463756752];

% Layer 2
b2 = 0.38340513149042693142;
LW2_1 = [-0.0005117328810776353154 -0.032846970585563080303 -0.0012022604364041618568 -0.16725847572015636877 -0.00015703491206091885614 1.5332606141782114673 0.00028692772215838894135 -0.00045553360384485133607 0.001973670618386759619 1.6932929981814948128];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000176304654442877;
y1_step1.xoffset = 6011;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
