function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 20:22:03.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [-0.62651617232393363999;-0.17915146345281929285;-1.3007029561197147594;1.7805519960316404937;-1.2304013946583820527;0.87376395769329573415;-0.40792530382027936131;1.4307012246095902608;0.89728149469243967395;0.3815143147195121931];
IW1_1 = [0.53527118672650220166 0.32486154462896787987 0.22593729957048683255 0.31155911558450799514;3.4793288128486401511 3.2388493288467374853 0.17165829822847739061 -2.5349195074950969797;-1.0329043015915011505 -4.9506526725532360445 -1.2071612944695293557 -3.887763879585710125;4.295929556921214143 2.4020766417074215227 -0.61228717547207289762 0.71342619298823273244;-1.9104851171204699778 3.3870968918526522806 4.5829312633246148678 -2.0323487639412336492;-22.008358777523337579 -21.92393102352890466 16.323118211076799611 16.758096449784630977;-3.9557793300530867953 -2.5644554881890515574 -2.0294571647639267908 -1.5962616258849937623;-0.3379334873595348232 3.6290816434051973438 0.27261760084427472117 0.11519863717396282288;0.65926374971490986354 0.41335615657827129432 0.059004803053615578756 1.1130764496133787045;0.017851221362458608716 -0.080883741855823018674 -0.43619449361938023024 -0.57235419843050749922];

% Layer 2
b2 = -0.8908928300155890545;
LW2_1 = [-2.213327330756963196 -0.0034029399191044841511 -0.00042531612576072764251 0.003439276716327607699 -0.00083145615143462585535 -0.00080756445735995717981 -0.021548363404659150872 0.0017262645534718216826 0.15608498294205783163 -1.7666225801791388683];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000197745699031046;
y1_step1.xoffset = 0;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
