function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 20:33:46.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [-2.7085883417290026465;1.0990353319445997915;2.8243972085302764263;0.86153220934434737721;0.63574728782489853263;0.097472863976733797875;-0.84426795141600541328;1.3783984986880366552;-0.7857842797816241287;-2.9942813008659565632];
IW1_1 = [0.022105655799677909057 -0.93890355167465799902 -2.0852971017129084963 1.6361196093666083851;-0.80097255904695685569 -0.34734760888221993813 -0.48718973883275129566 -0.48183773481280528506;-3.9776927306096210302 2.7942155054113695378 1.8931788153639508288 -0.46583034453918020779;-1.4419979757632137574 0.90597526781518289418 1.1269549444286595108 1.9137678338931194411;-0.10815674420753697282 -0.47477471716247870992 -0.06966984153181947359 -0.046071273420859031045;0.13652873083340510973 -0.13838317275782729965 -0.049189479393833036858 0.082799620844808921594;-1.1214394526454760648 -1.5117619210659654083 -0.63761945397161223781 1.1856759351723116236;0.45727880986564972687 1.9593233720751925819 -2.284548883648282569 -0.24773985738846612814;-0.095533879480566158415 -0.4888723327401087726 0.033031263332990584702 -0.050492130745903127109;-3.3672674767981147781 1.2265363658057413243 -0.71818383730613577498 1.7242551838205848469];

% Layer 2
b2 = -0.081664647054312852759;
LW2_1 = [-0.0014227019178978765872 0.090933988121657857717 0.00052927944623545430773 -0.0002805802638573076397 -1.3986048186017738804 -1.287742011941916731 0.0010614148872667534488 -0.0019839110896209856405 -1.453190299713684297 -6.418144476865156984e-05];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000687521485046408;
y1_step1.xoffset = 1574;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
