function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 20:36:49.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [2.8313936608585561494;-1.2789096298932542961;-1.3511755727302685592;2.3967634581843615393;0.58376779644782073042;2.1547408909596321713;0.11808500633596744067;0.91518952722497315388;3.0760255895229557943;0.014596585621645171565];
IW1_1 = [-2.3508368058283286572 2.5867144140067823699 -0.33044546687970838272 -0.10853485308054340586;-0.95701906638590439336 -0.20709648749000353352 0.48406053799012904726 0.19011202187051343127;-0.21703555099102148085 -0.6733786844711633357 -0.47145088316253808136 -1.6185957658033744977;0.46151204169864179505 -2.9714683628418763206 2.4246891685056017884 5.6472423780930052217;1.2913695061756309546 0.83535811322050312899 1.0462903143164936637 0.70088464679113815503;2.2971243035418811296 1.1025650582340513761 0.35682586322208664775 4.002938882703801049;-0.34939798361178492359 -0.098560041155759017806 -0.30290108685293581914 -0.33289210412429592889;0.42472022977800610866 -0.30894952419117499565 -3.4703075917686390106 -2.5907603973975827927;1.6401109222066319049 0.077956629686417575065 1.6594674141818883673 -2.7135893755766660185;-2.5133187173771780465 0.091813286211804845394 2.565904601120246209 -0.94173625763029622515];

% Layer 2
b2 = 0.54036665383477722191;
LW2_1 = [-0.012745750145654613505 -0.072190638120573705216 -0.22600131065222786586 -0.0011944782289516457392 -0.43208643306592298128 0.0067888513789114857816 -3.4751773683394171499 0.0019592355728373341342 0.0029504875617376862158 -0.0071113626927230659536];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000464252553389044;
y1_step1.xoffset = 2454;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
