function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 20:42:02.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [6.3406134011758146229;-2.8224979571274877443;3.5029069795150524769;-36.88070539946786397;1.8586772366874659834;0.52024947269221299972;-0.56176696748106824675;10.345034364881252387;3.9343940504866536934;-47.7140919917559998];
IW1_1 = [-3.6585726223102605914 -8.5199226848124123279 -18.873188304616284938 -6.9554787258391632676;11.507050477633704588 4.3965716287251135341 26.104349919265491309 -2.998438938332071757;-0.68618378882776009942 3.8235989918579522673 0.74874787664056197123 -1.6484436964287767502;-35.742315927680088805 -136.25790432656768303 -188.11453187750538518 29.101538796343835003;-12.938705132267328324 -9.4275386898639617073 -16.801111286190231198 -31.434454536827526994;-0.0046343907495879303055 -0.40325206753600334464 0.11116025472920197659 -0.027813978985981886033;-0.014421370940525219534 0.59217549461644558573 0.2131928512514559837 0.028146621215243836783;-14.150048889641023919 20.789946739803543352 -24.67287772449732941 -19.027560523903463974;3.3045471008170803628 -1.3431122277561358125 -1.2863757455377011762 5.6249585354879867438;64.688332282316110877 72.649568564894181577 153.71405615441469195 -29.70164030261198107];

% Layer 2
b2 = 0.88316909120499131891;
LW2_1 = [0.0069153131029073590386 1.9224047838499642055e-05 0.0060481647399065431234 -0.00035281872717217769263 6.5118386986446558985e-05 -4.3201509836197997672 -2.0237456490727234737 0.0013314828687330186163 -0.0045217943814599374092 -0.0016010141565792788357];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000838574423480084;
y1_step1.xoffset = 88;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
