function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 20:47:58.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [-2.6146179162309803878;-1.8940036223992628983;1.8611247360609954882;0.35960621239043116804;0.58893987417723114852;-0.91797659868406589201;0.34413014528497332112;0.7982284691816650124;2.5031870961467244108;-1.4196351803664049029];
IW1_1 = [1.6714673750149984244 0.63028537467038292519 -1.6623902510348447237 -1.0283241267971288124;0.4295590841873992427 -1.0309575136704063336 0.51576624539077486897 -2.0262438428342379737;0.16325258616119181498 0.74871035611387282138 -1.8307325326518795183 0.43806589130151390998;-0.15867762360686571421 0.9261343095346248333 -0.78152123689858821187 1.3521986916302812798;-0.0031628229294722145018 0.0052632513794431722357 -0.34513523900181880544 0.0044432541631645120633;-2.763422998799912822 -4.6350556380614165164 2.6007638578632259474 -2.4412444310699457084;0.020392342884992666757 0.55570470105644453884 -1.4950560733040156869 1.2617037714757488587;-0.0011699010425849135607 -0.0033040940900580548049 0.50492579183081243155 0.0024880079275346428207;2.3482457157977019158 -0.45948653226907310021 1.3867223352796744784 -2.3303576101390781616;-0.11036579028270220026 0.060493138662755158164 0.094281375031146599786 0.064125875300608592422];

% Layer 2
b2 = 0.80941049187583458124;
LW2_1 = [0.000832614986501486261 -0.0020779568662757006391 0.0055945451258493225297 0.0021780918515260788704 -2.5890481108169010049 3.385603186274576136e-05 -1.4656109205692018711e-05 1.2360160334767003043 -2.3215210059537754378e-05 0.29716499348479891163];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000431406384814495;
y1_step1.xoffset = 2140;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
