function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 20:58:31.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [-1.9276383189836518994;-1.0777922798093197976;-1.1393396886071180951;-0.15802007343809493234;-0.36527651172812924951;0.49398599179684166138;-0.95671237121196583963;1.0502841771999991138;-8.9948142036023384094;-2.5829907655838799663];
IW1_1 = [0.0028502707506617478393 0.025829662780465195704 -0.067744857871220226508 -0.31144665289111223005;-0.0015200306320298827625 -0.00058440894750852673614 -0.7032282865526571225 -0.001153108035968950602;-0.80842546393559799878 -1.3263558684096836693 -1.5055255026602563095 0.22999677190879563859;0.1065566899383027788 0.33667275461419698956 0.74053922944710337539 0.22033061758635660854;-0.00096396795830675429881 -0.0011178376842423270749 0.36220991817738656948 -0.0013038135932440253224;0.38689566614303633196 -0.1512110967614639645 -0.73784025230296690356 0.10829290182300331524;0.14420871711978508478 0.18583415933463998115 2.5790544045473700052 0.024807723087334868778;-2.0234246324694451502 -3.2566205772302572186 0.39690615902290005135 -4.3345888308906683761;-7.2856728086979858361 -2.2082428132460845127 2.161879878351097517 10.85352228213860748;-0.50239283521882860395 -1.2534902599227730757 2.7143397422616053483 3.0652623539996723956];

% Layer 2
b2 = 0.40810267583478326836;
LW2_1 = [0.044911228508734871157 -0.67401407877621000164 -0.00046780306964405916252 0.015178074854430302285 2.5762817456606197375 0.0034126754118517458464 -0.0025920580626655103165 -3.956942843389206233e-05 -1.188231986080243685e-05 2.9928922353681284646e-05];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000172369214858226;
y1_step1.xoffset = 5314;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
