function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 21:04:10.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [8251;8049;7454;8005];
x1_step1.gain = [0.000153280196198651;0.000125857403561765;0.000123160293121498;0.000131778348817289];
x1_step1.ymin = -1;

% Layer 1
b1 = [0.14980153744183263842;1.8210154023764033582;0.60259894246454437372;-0.42247562018040668574;-0.68217175723370448992;2.6406353313372101788;0.86111321651997130289;1.349149230973900826;3.4916520733918878783;-2.8266074037075821224];
IW1_1 = [1.2369589102641675993 2.022672354243367554 -1.3087660534655956024 1.9905939386599049712;-1.4305942752370308657 -0.98197947293136467195 -0.59284740029577753795 -1.0191300287589237783;-0.26023218293026517678 -0.061318360347348457862 -0.47696186111174221356 -0.43163321732135689901;0.30981991204670900064 0.11750484440502126371 0.0070220127255559957116 0.48835971616284562513;0.64315055403301557568 0.026358954403116620357 -1.112735894362959721 -1.4024223206480153081;-0.064140346541298964844 0.47474315388158033757 1.9288944022211413909 2.4871995005492499864;0.44683848111980123408 0.053349661969796458028 -0.26951154984704051021 1.0781117790510388321;0.91365288886204731877 -0.23128051557890311196 1.965436872384567879 0.88178934645563433747;1.7170958278210182169 -1.9289807868862518525 -0.77325560306504725894 2.9940842621930707779;-1.2504404883044519803 1.0647936619977762529 2.5069996388581659019 0.7024084715176427407];

% Layer 2
b2 = 0.43063482598811347879;
LW2_1 = [0.0057300529050894498037 -0.92373083287494539562 1.9795013657769562343 2.2184535473868707278 -0.044224473386417072207 0.10993339641771711357 0.17448068392288867967 -0.057821838885473784975 0.011870100181989915941 -0.013667484982252986123];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.000189609404626469;
y1_step1.xoffset = 1387;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
