function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 17:01:49.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx1 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 637;
x1_step1.gain = 0.000223114680946006;
x1_step1.ymin = -1;

% Layer 1
b1 = [32.200440385195868487;9.6626548836414638544;3.6767053325214398285;-1.4253651868193129015;1.0349120429341336358;0.22295202400513358665;-1.5662870423615617987;-6.1498858018986908291;-11.601897676605489096;-12.81279802379336985];
IW1_1 = [-33.318957773224710195;-10.797220266743428496;-5.0285847432786328071;3.3947788361011959068;-6.5530374546763106025;2.8415705380383000644;-3.0143027666257293795;-9.0203362448219213121;-14.218855808425441722;-13.299452616816864747];

% Layer 2
b2 = -0.013500928508440188103;
LW2_1 = [-0.015447456020279578398 -0.04798924080011576776 -0.12660094629878138051 0.21572807157171189352 -0.019544610207667210272 0.24907432231237189302 -0.24559152287641827783 -0.03105544157039039771 -0.03495873878513205274 -0.067759915432850356676];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 2.14898712864159;
y1_step1.xoffset = 0.067162;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
