function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 15:36:22.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx1 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx3 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 637;
x1_step1.gain = 0.000223114680946006;
x1_step1.ymin = -1;

% Layer 1
b1 = [32.5079602571153643;10.547606469052903222;2.5859145622051120661;0.91405713285629497378;0.153883500062459877;1.9060625203208099165;4.7900322695721211375;-5.1699769747201989034;2.7729606395334207569;-11.969023812617882285];
IW1_1 = [-33.172034213243016154;-10.911907221596598205;-3.1083483008713397311;-2.6594178996351898192;-5.7756729014773577902;13.307546863174490426;16.632006200317501765;-11.92167749576910829;4.0394810775879674836;-12.540085069418323016];

% Layer 2
b2 = [0.0087860593387679708499;-0.072486523736085814451;0.047834979067505098427];
LW2_1 = [-0.25658605402524292671 -0.066491631062633296811 -0.15891106344500205427 -0.20803872791754488003 -0.060080409715972671325 0.029694578559300216503 0.028096079569032997303 -0.032564458511030291987 0.17389594177176184719 -0.038350926282975393578;-0.26232037280232717302 -0.036753734314087328772 -0.14901154569623301094 -0.19331654140367798833 -0.049220595089937535516 0.026651178945402566323 0.028509786451255923756 -0.027920905394917101827 0.15532921008825781306 -0.036214929470140995449;0.0013989574889834660663 -0.02455416898517488733 -0.23746783673027355155 -0.31118335725223195132 -0.088786221703416268181 0.042976589004218704315 0.045067056332107939542 -0.046840564086189029336 0.26184442704109617273 -0.057278644567985849412];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = [2.09569136334154;2.53103043310993;2.14898712864159];
y1_step1.xoffset = [0.045579;0.033046;0.067162];

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
