function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 16:41:50.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx2 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [0;637];
x1_step1.gain = [0.000337552742616034;0.000223114680946006];
x1_step1.ymin = -1;

% Layer 1
b1 = [2.8220426803393339199;-2.2225591829179078829;-3.5666240469485304132;1.147926009724325791;-0.059308472840061327025;-0.86318512994133367311;-2.2603390206300653098;-0.1112963756858069142;-2.2967854878315159262;4.0102184854057476571];
IW1_1 = [-0.57999196689359711065 -4.0495311083300702393;1.1923662825449157232 1.9964910813947931434;2.4623518924434888433 -3.2995953486561635515;-2.4591951522509964967 4.0252276268157833883;-3.394535314979584939 3.6190092373219222566;-1.7417370536193288455 -0.8737563333643899588;-4.1645877317299335729 0.20486038210248572189;-0.3836511309894993782 -0.72986536290723225129;-1.664999676628500902 -2.0049241109440751885;2.0264230801849967278 2.0313384901596664989];

% Layer 2
b2 = -0.078695841409536823607;
LW2_1 = [-0.0085371864825506266206 0.21901759771356418827 -0.010969392939858754743 -0.070171106159848908868 0.079511881434629644305 -0.070200096946139073362 -0.0062197116263555847493 -0.77087188127983663488 -0.051223076295254577062 0.17307968812840643369];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 2.09569136334154;
y1_step1.xoffset = 0.045579;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
