function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 16:53:15.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx2 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx1 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [0;637];
x1_step1.gain = [0.000320975766329642;0.000223114680946006];
x1_step1.ymin = -1;

% Layer 1
b1 = [4.4230906207807958452;-2.6558609307896148266;2.3499355163495776466;-1.6441881871735963827;0.043795511961384168964;0.39296482190550235947;-1.0969599686034192665;-2.6223974422157900754;2.2357489910850336656;4.6570271133733678326];
IW1_1 = [-2.3880214360164528919 3.729983647067826702;1.0879825603331643169 2.3270710102366884975;-1.6630681995729659217 3.9372648792924667127;0.013610542883656406507 -3.1077056787395784809;0.19317283072787835851 0.27676513907951189042;3.1095650159906127463 -2.5706651771331534562;-4.4926221213686323708 0.67077521034440379388;-0.39851906255451674532 -4.3776673425243473048;2.3697848940567629583 3.5568745898459255272;3.0062077519426022576 2.0961219739641578919];

% Layer 2
b2 = 0.031715810937463194408;
LW2_1 = [-0.12613439781904467463 0.035636377826076398589 0.024188800602769258002 -0.020028452282504979887 2.1161424494124747575 0.01430619162955981509 -0.00018651981625011812256 0.0074339889850297755092 0.0019728221650002477836 0.014425948396331650728];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 2.53103043310993;
y1_step1.xoffset = 0.033046;

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
