function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 14-Oct-2018 15:10:35.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx1 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx3 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 431;
x1_step1.gain = 0.000192678227360308;
x1_step1.ymin = -1;

% Layer 1
b1 = [-15.326478416704309993;-10.893554602813210863;6.1930710616376511979;-2.7818370835711001554;-0.73936024827594959419;-0.99563653453670786231;-0.85815156234095069099;2.7945421706392425953;7.493423362065097848;13.062643683958645724];
IW1_1 = [12.673465867529355222;13.969761827264632004;-14.57789289648517439;11.894262618370095907;9.4491384459656071471;-11.825109621723136399;-3.3371802162415677984;4.3492882837283186603;8.9049574852553448068;13.33291320285180781];

% Layer 2
b2 = [-0.41261916164746881286;0.058961370606773207126;0.20644638499701167822];
LW2_1 = [-0.36507328995456056475 0.0028809981681259247063 -0.0013620100897846238331 0.085803840986994839302 0.0991151168335804994 -0.030427211797107358432 -0.40733731983308701929 0.25157712542109067488 0.088757818692842008201 0.079789034651381207652;0.1116005004246487381 0.0027003901127944244034 -0.0013038483427894862789 0.085744108797541657152 0.098025655892719776308 -0.030679202183281233107 -0.4044386882656448301 0.25077549912842073132 0.087866945774634927502 0.07955733106206272498;0.28004623148715912517 -0.0015055741823414110422 0.0082259810400507667877 -0.016085087016354672473 -0.063223276846802761719 0.11650687147059297921 -0.62802763123538785095 0.38820902459361700254 0.13797921905372553808 0.12351415538252481785];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = [2.12714362899212;2.82642366960238;2.20399275327183];
y1_step1.xoffset = [0.059771;0.044539;0.088929];

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = repmat(b2,1,Q) + LW2_1*a1;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a2,y1_step1);
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
x = bsxfun(@minus,y,settings.ymin);
x = bsxfun(@rdivide,x,settings.gain);
x = bsxfun(@plus,x,settings.xoffset);
end
